name: CI

on:
  push:
    branches:
    - main
    tags:
    - '*'
  pull_request:
  schedule:
    - cron: "0 3 * * *"

jobs:
  tests:
    runs-on: ubuntu-latest
    name: ${{ matrix.python-version }} with all dependencies
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install tox
      run: python -m pip install --upgrade tox
    - name: Python ${{ matrix.python-version }} with astropy
      run: |
        # remove "." from matrix.python-version to get the defaults tox python versions
        tox_python_target=$(echo py${{matrix.python-version}} | sed 's/\.//')
        echo "Tox python target: " $tox_python_target
        tox -e $tox_python_target-test-alldeps


  mac_windows:
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} with mandatory dependencies
    needs: tests
    strategy:
      fail-fast: true
      matrix:
        os: [macos-latest, windows-latest]
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Install tox
      run: python -m pip install --upgrade tox
    - name: Python 3.9 with latest astropy
      run: tox -e py39-test


  stylecheck:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install tox
        run: python -m pip install --upgrade tox
      - name: Check codestyle
        run: tox -e codestyle


  devdeps:
    # TODO: this job should be allowed to fail except that the functionality
    # is not available in actions yet.
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install tox
        run: python -m pip install --upgrade tox
      - name: Run tests against dev dependencies
        run: tox -e py310-test-devdeps-alldeps-cov

      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          verbose: true



  oldestdeps:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install tox
        run: python -m pip install --upgrade tox
      - name: Run tests against oldest dependencies
        run: tox -e py38-test-oldestdeps
